-- 코드를 입력하세요
SELECT B.BOOK_ID, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK B
where date_format(PUBLISHED_DATE, '%Y') = '2021'
GROUP BY CATEGORY
HAVING CATEGORY = '인문'
order by B.PUBLISHED_DATE asc